---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: control-plane
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: control-plane
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: control-plane
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: control-plane
subjects:
- kind: ServiceAccount
  name: control-plane
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: control-plane
spec:
  ports:
  - name: grpc
    port: 18000
    protocol: TCP
    targetPort: 18000
  selector:
    app: control-plane
    purpose: control-plane
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-plane
spec:
  replicas: 1
  selector:
    matchLabels:
      app: control-plane
      purpose: control-plane
  template:
    metadata:
      labels:
        app: control-plane
        purpose: control-plane
    spec:
      # START FOCUS OMIT
      containers:
      - name: go-test-app
        image: carsonoid/go-test-app
        args:
        - /control-plane-kube
        imagePullPolicy: Never # OMIT
        resources: {} # OMIT
        terminationMessagePath: /dev/termination-log # OMIT
        terminationMessagePolicy: File # OMIT
      # END FOCUS OMIT
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      serviceAccountName: control-plane
